feat: implement fetch user
alexandrabakhar/frontendiya pull request #9
Opened 2024-04-05 17:56 UTC by alexandrabakhar

Also add context, tanstack query for fetch user

2024-04-07 10:25 UTC, remadyt requested changes

2024-04-07 10:25 UTC, remadyt commented on src/app/layouts/MainLayout.tsx
> +  const contentType = errorStatus === '404' ? 'user' : 'initial'
if 500 erorStatus?

2024-04-07 10:25 UTC, remadyt commented on src/features/search-user/ui/SearchForm.tsx
> +type SearchFormValues = {
prettier work?

2024-04-07 10:25 UTC, remadyt commented on src/entities/user/model/UserContext.ts
> +  setIsLoading: React.Dispatch<React.SetStateAction<boolean>>
why need ``` React.```? use ```Dispatch<SetStateAction<boolean>>```

2024-04-07 10:25 UTC, remadyt commented on src/app/providers/UserContextProvider.tsx
> +import { UserContext } from '@/entities/user/model/UserContext'
fix imports here and all such places , as sample look. https://feature-sliced.design/ru/docs/guides/examples/auth

2024-04-08 09:09 UTC, alexandrabakhar commented on src/features/search-user/ui/SearchForm.tsx
> +type SearchFormValues = {
yes, but settings don't include rules about empty string after imports

2024-04-08 09:22 UTC, alexandrabakhar commented on src/app/layouts/MainLayout.tsx
> +  const contentType = errorStatus === '404' ? 'user' : 'initial'
So I need another page like 'everything was broken, wait a minute to continue'

2024-04-08 10:48 UTC, alexandrabakhar commented on src/app/layouts/MainLayout.tsx
> +  const contentType = errorStatus === '404' ? 'user' : 'initial'
added defaultError content for empty block (for other errors)

2024-04-09 05:55 UTC, remadyt requested changes

2024-04-09 05:55 UTC, remadyt commented on src/entities/user/hooks/useUserContext.tsx
> +import { User } from '@/entities'
not need 2 imports from entities, add eslint rule for handle this

2024-04-09 05:55 UTC, remadyt commented on src/entities/user/model/UserContext.ts
> +type UserContextType = {
type not needed in naming

2024-04-09 05:55 UTC, remadyt commented on src/entities/user/model/UserContext.ts
> +  user: User | null
implement Nullable helper, type Nullable<T> = T | null, and declare in global.d.ts

2024-04-09 05:55 UTC, remadyt commented on src/entities/user/ui/card/Card.tsx
> +import { FollowersIcon, FollowingIcon, useUserContext } from '@/entities/user'
from  @/entities

2024-04-09 05:55 UTC, remadyt commented on src/entities/user/ui/card/Card.tsx
> +          {/* TODO: сделать форматирование тысячи */}
why not implemented?

2024-04-09 05:55 UTC, remadyt commented on src/features/search-user/ui/SearchForm.tsx
> +import { baseQuery } from '@/shared/api/baseQuery'
from shared/api

2024-04-09 05:55 UTC, remadyt commented on src/features/search-user/ui/SearchForm.tsx
> +  const handleOnSubmit: React.FormEventHandler<
remove ```React. ```

2024-04-09 05:55 UTC, remadyt commented on src/pages/EmptyPage/ui/EmptyPage.tsx
> +    ? error === '404'
refactor, nested ternary - bad practice. use switch case or mapper pattern

2024-04-09 05:55 UTC, remadyt commented on src/pages/EmptyPage/ui/EmptyPage.tsx
> +export const EmptyPage: FC<EmptyPageProps> = ({ error }) => {
need all components type on 1 style. ```FC<Props> or ({}: Props)```

2024-04-09 05:55 UTC, remadyt commented on src/pages/MainPage/ui/MainPage.tsx
> +      {user?.repos_count === 0 ? (
move to const ````user?.repos_count === 0```

2024-04-09 05:55 UTC, remadyt commented on src/widgets/Repositories/api/fetchRepositories.ts
> +}: {
move to separate type ```{
  username: string
  perPage: number
  page: number
}```

2024-04-09 05:55 UTC, remadyt commented on src/widgets/Repositories/hooks/useRepositories.tsx
> +import { getTotalPages } from '@/widgets/Repositories/lib/getTotalPages'
fix imports

2024-04-09 05:55 UTC, remadyt commented on src/widgets/Repositories/hooks/useRepositories.tsx
> +  const [repoCountPerPage, setRepoCountPerPage] = useState(1)
do not use magic numbers

2024-04-09 05:55 UTC, remadyt commented on src/widgets/Repositories/ui/Repositories.tsx
> +
remove empty line

2024-04-09 05:55 UTC, remadyt commented on src/widgets/Repositories/ui/Repositories.tsx
>    const [currentPage, setCurrentPage] = useState(1)
do not use magic numbers

2024-04-09 05:55 UTC, remadyt commented on src/widgets/Repositories/ui/Repositories.tsx
> +          return (
obvious return not needed

2024-04-09 14:07 UTC, merged